use CHARM_DIR instead of a hardcoded path.

diff --git a/hooks/swift-storage-node-common b/hooks/swift-storage-node-common
--- a/hooks/swift-storage-node-common
+++ b/hooks/swift-storage-node-common
@@ -2,11 +2,12 @@
 set -ue
 
 CHARM="swift-storage"
+HOOKS_DIR="$CHARM_DIR/hooks"
 
-if [[ -e "$CHARM_DIR/lib/openstack-common" ]] ; then
-  . $CHARM_DIR/lib/openstack-common
+if [[ -e "$HOOKS_DIR/lib/openstack-common" ]] ; then
+  . $HOOKS_DIR/lib/openstack-common
 else
-  juju-log "ERROR: Couldn't load $CHARM_DIR/lib/openstack-common." && exit 1
+  juju-log "ERROR: Couldn't load $HOOKS_DIR/lib/openstack-common." && exit 1
 fi
 
 DEFAULT_ETH=$(ip route  | grep default | awk '{ print $5 }')
